apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: mysql
  annotations:
    kubesphere.io/alias-name: mysql root 密码
    kubesphere.io/creator: hjf
type: Opaque
data:
  password: MTIzNDU2 # echo -n '123456' |base64
