apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  labels:
    app: mysql
data:
  master.cnf: |
    # Apply this config only on the master.
    [mysqld]
    datadir=/var/lib/mysql
    # 设置native_password身份验证插件的密码
    authentication_policy=mysql_native_password
    # 关闭MySQL对创建存储过程、函数的限制
    log_bin_trust_function_creators=1
    # 复制过滤：也就是指定哪个数据库不用同步（mysql库一般不同步）
    binlog-ignore-db=mysql
    # 开启二进制日志功能，可以随便取，最好有含义（关键就是这里了）
    log-bin=mysql-bin
    # 为每个session分配的内存，在事务过程中用来存储二进制日志的缓存
    binlog_cache_size=1M
    # 主从复制的格式（mixed,statement,row，默认格式是statement）
    binlog_format=mixed
    # 二进制日志自动删除/过期的时间。
    binlog_expire_logs_seconds=0
    # 跳过主从复制中遇到的所有错误或指定类型的错误，避免slave端复制中断。
    # 如：1062错误是指一些主键重复，1032错误是因为主从数据库数据不一致
    replica_skip_errors=1062
    # gtid
    enforce_gtid_consistency=ON
    gtid_mode=ON
    # 忽略库名表名大小写
    lower_case_table_names=1
    # 数据库默认引擎
    default-storage-engine=INNODB
    character-set-client-handshake=FALSE
    # 服务端默认编码格式
    character-set-server=utf8mb4
    # 服务端默认排序规则
    collation-server=utf8mb4_unicode_ci
    bind-address=0.0.0.0
    
  slave.cnf: |
    # Apply this config only on slaves.
    [mysqld]
    super-read-only
    datadir=/var/lib/mysql
    # 设置native_password身份验证插件的密码
    authentication_policy=mysql_native_password
    # 关闭MySQL对创建存储过程、函数的限制
    log_bin_trust_function_creators=1
    # 复制过滤：也就是指定哪个数据库不用同步（mysql库一般不同步）
    binlog-ignore-db=mysql
    # 开启二进制日志功能，可以随便取，最好有含义（关键就是这里了）
    log-bin=mysql-bin
    # 为每个session分配的内存，在事务过程中用来存储二进制日志的缓存
    binlog_cache_size=1M
    # 主从复制的格式（mixed,statement,row，默认格式是statement）
    binlog_format=mixed
    # 二进制日志自动删除/过期的时间。
    binlog_expire_logs_seconds=0
    # 跳过主从复制中遇到的所有错误或指定类型的错误，避免slave端复制中断。
    # 如：1062错误是指一些主键重复，1032错误是因为主从数据库数据不一致
    replica_skip_errors=1062
    # gtid
    enforce_gtid_consistency=ON
    gtid_mode=ON
    # relay配置(https://www.cnblogs.com/determined-K/p/14692845.html)
    relay_log_info_repository=table
    master_info_repository=table
    relay_log_recovery = 1
    # 忽略库名表名大小写
    lower_case_table_names=1
    # 数据库默认引擎
    default-storage-engine=INNODB
    character-set-client-handshake=FALSE
    # 服务端默认编码格式
    character-set-server=utf8mb4
    # 服务端默认排序规则
    collation-server=utf8mb4_unicode_ci
    bind-address=0.0.0.0
